### ISSUE TITLE
Build not failing with error when a vendored application is built with unmet dependencies

### ISSUE THREAD

**Issue by arjun024** [paketo-buildpacks/yarn-install#134]
I expect that when I remove a module from `node_modules` in this [app](https://github.com/paketo-buildpacks/yarn-install/tree/v0.2.0/integration/testdata/vendored), the build fails with an error that the vendored application has unmet dependencies. But as of now, the build succeds.

See how npm-install buildpack makes sure that [build errors on unmet dependencies for vendored apps](https://github.com/paketo-buildpacks/npm-install/blob/v0.2.1/rebuild_build_process.go#L44-L54), I would expect yarn-install to have consistent behavior

**Comment by fg-j** [comment]
If a vendored app is built once, then contents of `node_modules` removed entirely, then the app is built again, the buildpack reuses the cached modules layer and still builds *and runs* successfully despite the vendor directory of the source code being mangled. This seems like confusing behaviour, even though it doesn't cause the app to break.

To reproduce with [this app](https://github.com/paketo-buildpacks/yarn-install/tree/main/integration/testdata/vendored)
```
pack build change-node-modules  -b gcr.io/paketo-buildpacks/nodejs:0.0.10 --builder paketobuildpacks/builder:0.1.17-base
```
then, rip out the `node_modules/leftpad` directory and `pack build` again.

**Comment by fg-j** [comment]
In the online case, if the buildpack rebuilds the node modules layer, it runs: [`yarn install --ignore-engines --frozen-lockfile --modules-folder /path/to/modules/layer/node_modules`](https://github.com/paketo-buildpacks/yarn-install/blob/20edf8b86d9b0ef76590555ba15e1463efd6db12/install_process.go#L108). 

Given that the [expected behaviour](https://classic.yarnpkg.com/en/docs/cli/install/#toc-yarn-install) of this command is to "install all the dependencies listed within package.json in the local node_modules folder", I think it's reasonable for the online buildpack to repopulate a `node_modules` that is missing dependencies and build the app successfully. This is the current behaviour. Even though it differs from the npm-install buildpack, it's more consistent with how yarn itself works.

In the offline case, a [bug in our yarn config parsing](https://github.com/paketo-buildpacks/yarn-install/issues/154) means that the buildpack can't currently find the offline mirror. If that's fixed, the build should probably only fail if a dependency is missing from `node_modules` _and_ from the offline mirror directory. Yarn already throws an error in that case, which looks something like:

```
 yarn install v1.22.10
[1/4] Resolving packages...
[2/4] Fetching packages...
error Can't make a request in offline mode ("https://registry.yarnpkg.com/leftpad/-/leftpad-0.0.1.tgz")
```
