### ISSUE TITLE
Bad node_modules symlink when cache is used

### ISSUE THREAD

**Issue by fgrehm** [paketo-buildpacks/yarn-install#397]
## Expected Behavior

`node_modules` should be symlinked to the right directory at all times, regardless of cache layers used and other collaborating buildpacks

## Current Behavior

When I run the second build of a node app with cache enabled I noticed that the `node_modules` directory is symlinked to the wrong path

## Possible Solution

I think this `!build` here might be the root cause?

https://github.com/paketo-buildpacks/yarn-install/blob/07f74166aade91f6da65c913f58aa4264460bf94/build.go#L261-L271

## Steps to Reproduce

See [this gist](https://gist.github.com/fgrehm/3211d96677dabd247035566a3d5664f5#file-01-run-bash) and [output logs](https://gist.github.com/fgrehm/3211d96677dabd247035566a3d5664f5#file-02-logs-txt). Notice that the build `#3` [yields a broken `node_modules`](https://gist.github.com/fgrehm/3211d96677dabd247035566a3d5664f5#file-02-logs-txt-L983-L1008) while build `#2` [passing in `--clear-cache`](https://gist.github.com/fgrehm/3211d96677dabd247035566a3d5664f5#file-01-run-bash-L42) works [fine](https://gist.github.com/fgrehm/3211d96677dabd247035566a3d5664f5#file-02-logs-txt-L682-L692)

## Motivations

This is what is happening under the hood for us with the custom buildpack I mentioned in https://github.com/paketo-buildpacks/rails-assets/issues/248

**Comment by mterrel** [comment]
We're also unable to upgrade Adaptable.io use to the latest versions of this buildpack (or the builder versions that contain it) due to this bug. It appears to have been introduced by 325309e9c147c88b9b3588023d5cd386cf7c7313

It looks like @fgrehm already included a great repro, but I'm happy to help with more info as needed. And one thing that initially tripped me up while trying to create a manual repro: make sure you do not have a `node_modules` directory in your workspace.

**Comment by ryanmoran** [comment]
@fgrehm give this a shot: https://github.com/paketo-buildpacks/yarn-install/releases/tag/v0.10.7

**Comment by fgrehm** [comment]
Thanks folks! I'm giving this a shot today and found some weird behavior again, lemme take a closer look and report back :crossed_fingers:
